export function createMobileArchitectureViolations() {
  return {
    duplicateTypes: [],
    defaultExports: [],
    featureRootComponents: [],
    featureRootHooks: [],
    featureToAppImports: [],
    hardcodedText: [],
    inlineScreenProps: [],
    inlineScreenStyles: [],
    lineCounts: [],
    localContractPicks: [],
    localeSections: [],
    materialIconPrivateImports: [],
    materialIconPropTypes: [],
    rawCollectionTypes: [],
    rootAppData: [],
    rootAppCards: [],
    rootAppHandlers: [],
    rootAppFeedback: [],
    rootAppNavigation: [],
    rootAppSettingsTools: [],
    rootAppShellData: [],
    rootAppStudy: [],
    rootSourceFiles: [],
    rootServices: [],
    serviceFacadeImports: [],
    rootPlatformServices: [],
    appDeepFeatureImports: [],
    appDataStateComposition: [],
    studyDomainFeatureImports: [],
    wildcardExports: []
  };
}
