const requiredCorrections = {
  "lemma-29-bez": { en: /without/i, hi: /बिना/, ur: /بغیر/, tags: /preposition/ },
  "lemma-47-stesti": { en: /luck/i, hi: /किस्मत/, ur: /قسمت/ },
  "lemma-60-prijit": { en: /come|arrive/i, hi: /आना|पहुँचना/, ur: /آنا|پہنچنا/ },
  "lemma-62-zeme": { en: /country/i, hi: /देश/, ur: /ملک/ },
  "lemma-74-druhy": { en: /second/i, hi: /दूसरा/, ur: /دوسرا/ },
  "lemma-88-film": { en: /movie|film/i, hi: /फ़िल्म|फिल्म/, ur: /فلم/ },
  "lemma-97-zadek": { en: /bottom|backside/i, hi: /नितंब|पिछला भाग/, ur: /کولہے|پچھلا حصہ/ },
  "lemma-98-sedet": { en: /fit|suit/i, hi: /फिट/, ur: /موزوں/ },
  "lemma-99-vole": { en: /crop/i, hi: /अन्न-थैली/, ur: /خوراک کی تھیلی/ },
  "lemma-112-mily": { en: /kind/i, hi: /दयालु/, ur: /مہربان/ },
  "lemma-120-stop": { en: /ban|suspension/i, hi: /प्रतिबंध/, ur: /پابندی/ },
  "lemma-123-doba": { en: /time|period|era/i, hi: /समय|अवधि|युग/, ur: /وقت|مدت|دور/ },
  "lemma-124-dokazat": { en: /manage|able|prove/i, hi: /कर पाना|साबित/, ur: /کر سکنا|ثابت/ },
  "lemma-125-zly": { en: /bad|mean|evil/i, hi: /^बुरा$/, ur: /^برا$/ },
  "lemma-145-bal": { en: /formal dance/i, hi: /नृत्य समारोह/, ur: /رقص کی محفل/ },
  "lemma-146-drink": { en: /drink/i, hi: /ड्रिंक|कॉकटेल/, ur: /ڈرنک|کاک/ },
  "lemma-163-kouzlo": { en: /magic|spell/i, hi: /जादू|मंत्र/, ur: /جادو|منتر/ },
  "lemma-177-talent": { en: /talent|ability/i, hi: /प्रतिभा|योग्यता/, ur: /صلاحیت|ہنر/ },
  "lemma-190-rozum": { en: /reason|common sense/i, hi: /बुद्धि|समझ/, ur: /عقل|سمجھ/ },
  "lemma-316-bastard": { en: /insult|illegitimate/i, hi: /नाजायज़/, ur: /ناجائز/ },
  "lemma-371-znacka": { en: /brand/i, hi: /ब्रांड/, ur: /برانڈ/ },
  "lemma-233-stopa": { en: /trace|footprint/i, hi: /निशान|पदचिह्न/, ur: /نشان/ },
  "lemma-257-lezet": { hi: /लेटना/, ur: /لیٹنا/ },
  "lemma-299-lov": { hi: /^शिकार$/, ur: /^شکار$/ },
  "lemma-506-spor": { hi: /विवाद|झगड़ा/, ur: /تنازع|جھگڑا/ },
  "lemma-536-horet": { hi: /जलना/, ur: /جلنا/ },
  "lemma-550-euro": { en: /currency/i, hi: /यूरो \(मुद्रा\)/, ur: /یورو \(کرنسی\)/ },
  "lemma-224-sladky": { hi: /मीठा/, ur: /میٹھا/ },
  "lemma-236-body": { en: /points/i, hi: /अंक|पॉइंट/, ur: /پوائنٹ|نمبر/ },
  "lemma-276-vstoupit": { en: /^to enter$/i, hi: /प्रवेश करना/, ur: /داخل ہونا/ },
  "lemma-399-kriz": { en: /cross/i, hi: /क्रॉस|सलीब/, ur: /صلیب/ },
  "lemma-428-akcie": { en: /shares?|stocks?/i, hi: /शेयर/, ur: /حصہ|شیئرز/ },
  "lemma-582-karma": { en: /karma/i, hi: /कर्म/, ur: /کرما/ },
  "lemma-617-kachna": { en: /duck/i, hi: /^बत्तख$/, ur: /^بطخ$/ },
  "lemma-649-pismeno": { en: /letter/i, hi: /अक्षर/, ur: /حرف/ },
  "lemma-635-panic": { en: /male virgin/i, hi: /कुंवारा/, ur: /کنوارا/ },
  "lemma-767-sach": { en: /check/i, hi: /शह/, ur: /شہ/ },
  "lemma-806-moucha": { en: /fly/i, hi: /मक्खी/, ur: /مکھی/ },
  "lemma-791-jasan": { en: /ash tree/i, hi: /ऐश वृक्ष/, ur: /ایش کا درخت/ },
  "lemma-856-onen": { en: /literary/i, hi: /साहित्यिक/, ur: /ادبی/ },
  "lemma-902-peceni": { en: /baking/i, hi: /बेकिंग/, ur: /بیکنگ/ },
  "lemma-943-neb": { en: /because/i, hi: /क्योंकि|चूँकि/, ur: /کیونکہ|چونکہ/ },
  "lemma-1112-zanedbani": { en: /neglect/i, hi: /^उपेक्षा$/, ur: /غفلت/ },
  "lemma-1126-propaganda": { en: /propaganda/i, hi: /^प्रचार$/, ur: /پروپیگنڈا/ },
  "lemma-1062-senza": { en: /great/i, hi: /शानदार/, ur: /شاندار/ },
  "lemma-1085-narkoman": { en: /drug addict/i, hi: /नशे का आदी/, ur: /منشیات کا عادی/ },
  "lemma-1122-rozkrok": { en: /crotch|groin/i, hi: /जाँघों/, ur: /رانوں/ },
  "lemma-1147-aji": { en: /dialect/i, hi: /बोली/, ur: /بولی/ },
  "lemma-1172-lis": { en: /press/i, hi: /प्रेस मशीन/, ur: /پریس مشین/ },
  "lemma-1232-lup": { en: /loot|plunder/i, hi: /लूट का माल/, ur: /لوٹ کا مال/ },
  "lemma-1235-holy": { en: /bare|bald/i, hi: /गंजा/, ur: /گنجا/ },
  "lemma-1238-pres": { en: /press \(machine\)/i, hi: /प्रेस मशीन/, ur: /پریس مشین/ },
  "lemma-1245-salsa": { en: /dance/i, hi: /नृत्य/, ur: /رقص/ },
  "lemma-1252-klarinet": { en: /clarinet/i, hi: /क्लैरिनेट/, ur: /کلیرنیٹ/ },
  "lemma-1260-sekunda": { en: /second/i, hi: /^सेकंड$/, ur: /^سیکنڈ$/ },
  "lemma-1306-squash": { en: /racket sport/i, hi: /रैकेट/, ur: /ریکیٹ/ },
  "lemma-1314-salto": { en: /somersault/i, hi: /कलाबाज़ी/, ur: /قلابازی/ },
  "lemma-1318-plachta": { en: /sail/i, hi: /^पाल$/, ur: /^بادبان$/ },
  "lemma-1368-swing": { en: /dance/i, hi: /नृत्य/, ur: /رقص/ },
  "lemma-1384-slavik": { en: /nightingale/i, hi: /बुलबुल/, ur: /^بلبل$/ },
  "lemma-1386-racek": { en: /gull/i, hi: /समुद्री पक्षी/, ur: /سمندری پرندہ/ },
  "lemma-1396-bridz": { en: /card game/i, hi: /ताश का खेल/, ur: /تاش کا کھیل/ },
  "lemma-1397-negativ": { en: /photography/i, hi: /फोटोग्राफी/, ur: /فوٹوگرافی/ }
};

module.exports = { requiredCorrections };
