import type { Card, ReviewGrade, ReviewState } from "@czech-flashcards/shared";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { StudySettings } from "../database";
import type { AccountPanel, AccountStudySummary } from "../features/account/AccountPanel";
import type { useStudyAnimations } from "../features/study/useStudyAnimations";
import type { SyncStatus } from "../sync";
import type { Panel, Screen } from "./appTypes";

export type StudyAnimations = ReturnType<typeof useStudyAnimations>;
export type WordValues = { cz: string; en: string; hi: string; ur: string; sentence: string; sentenceEn: string; tag: string };
export type CorrectionValues = Omit<WordValues, "tag">;
export type AccountPanelProps = React.ComponentProps<typeof AccountPanel>;

export type AppShellProps = {
  screen: Screen;
  panel: Panel | null;
  deck: Card[];
  cards: Card[];
  customCards: Card[];
  states: Record<string, ReviewState>;
  settings: StudySettings;
  savedCardIds: Set<string>;
  current: Card | null;
  revealed: boolean;
  grading: boolean;
  lastReviewCard: Card | null;
  sessionReviews: number;
  sessionTarget: number;
  reviewedToday: number;
  dailyGoal: number;
  sessionProgress: number;
  studyAnimations: StudyAnimations;
  query: string;
  syncStatus: SyncStatus;
  settingsNotice: string;
  toastMessage: string;
  accountEmail: string | null;
  authBusy: boolean;
  accountStudySummary: AccountStudySummary;
  supabase: SupabaseClient | null;
  editingCard: Card | null;
  dailyProgress: string;
  reviewInterval: (grade: ReviewGrade) => string;
  onSetPanel: (panel: Panel | null) => void;
  onSetScreen: (screen: Screen) => void;
  onStartStudy: () => void;
  onSelectCategory: (category: string) => void;
  onQueryChange: (value: string) => void;
  onStudySearchResult: (card: Card) => void;
  onToggleSaved: (cardId: string, showFeedback?: boolean) => void;
  onOpenCardEditor: (card?: Card | null) => void;
  onCloseCardEditor: () => void;
  onUndoLastReview: () => void;
  onGrade: (grade: ReviewGrade) => void;
  onAddWord: (values: WordValues) => void;
  onDeleteWord: (cardId: string) => void;
  onSaveCorrection: (values: CorrectionValues) => void;
  onChangeSettings: (settings: StudySettings) => void;
  onSyncNow: () => void;
  onRestoreJson: () => void;
  onImportCsv: () => void;
  onShuffleDue: () => void;
  onReviewAllNow: () => void;
  onExportProgress: () => void;
  onExportDeck: () => void;
  onAuthenticate: AccountPanelProps["onAuthenticate"];
  onSignOut: AccountPanelProps["onSignOut"];
};
